[2024-09-12T08:21:09.803420+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://127.0.0.1:8000/api/products/","method":"GET"} []
[2024-09-12T08:21:09.810235+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:21:09.897645+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:21:09.909869+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:23:20.681133+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://localhost/api/products/","method":"GET"} []
[2024-09-12T08:23:20.688674+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:23:20.770323+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:23:20.782141+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:24:20.095203+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://localhost/api/products/","method":"GET"} []
[2024-09-12T08:24:20.101710+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:24:20.182539+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:24:20.190230+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:26:43.946929+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://localhost/api/products/","method":"GET"} []
[2024-09-12T08:26:43.954074+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:26:44.042076+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:26:44.050671+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:32:39.117352+00:00] request.INFO: Matched route "api_productsget_product". {"route":"api_productsget_product","route_parameters":{"_route":"api_productsget_product","_controller":"App\\Controller\\ProductController::getProduct","id":"1"},"request_uri":"http://localhost/api/products/1","method":"GET"} []
[2024-09-12T08:32:39.124225+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:32:39.205221+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:32:39.213486+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:32:39.627989+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://localhost/api/products/","method":"GET"} []
[2024-09-12T08:32:39.628124+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:32:39.629807+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:32:39.630386+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:33:49.450303+00:00] request.INFO: Matched route "api_productsget_product". {"route":"api_productsget_product","route_parameters":{"_route":"api_productsget_product","_controller":"App\\Controller\\ProductController::getProduct","id":"1"},"request_uri":"http://localhost/api/products/1","method":"GET"} []
[2024-09-12T08:33:49.456902+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:33:49.536628+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:33:49.544565+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:33:49.965410+00:00] request.INFO: Matched route "api_productsget_all_products". {"route":"api_productsget_all_products","route_parameters":{"_route":"api_productsget_all_products","_controller":"App\\Controller\\ProductController::getAllProducts"},"request_uri":"http://localhost/api/products/","method":"GET"} []
[2024-09-12T08:33:49.965541+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:33:49.967292+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:33:49.967898+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:36:39.593406+00:00] request.INFO: Matched route "api_productsget_product". {"route":"api_productsget_product","route_parameters":{"_route":"api_productsget_product","_controller":"App\\Controller\\ProductController::getProduct","id":"1"},"request_uri":"http://localhost/api/products/1","method":"GET"} []
[2024-09-12T08:36:39.600201+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:36:39.680903+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_pgsql","idle_connection_ttl":600,"host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app_test","serverVersion":"16","charset":"utf8"}} []
[2024-09-12T08:36:39.688984+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2024-09-12T08:39:42.369301+00:00] request.INFO: Matched route "api_productsget_product". {"route":"api_productsget_product","route_parameters":{"_route":"api_productsget_product","_controller":"App\\Controller\\ProductController::getProduct","id":"1"},"request_uri":"http://localhost/api/products/1","method":"GET"} []
[2024-09-12T08:39:42.376406+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:39:42.459084+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test","serverVersion":"8.0.3","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test","serverVersion":"8.0.3","charset":"utf8"}} []
[2024-09-12T08:39:42.469653+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'week5api_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)"} []
[2024-09-12T08:40:49.279674+00:00] request.INFO: Matched route "api_productsget_product". {"route":"api_productsget_product","route_parameters":{"_route":"api_productsget_product","_controller":"App\\Controller\\ProductController::getProduct","id":"1"},"request_uri":"http://localhost/api/products/1","method":"GET"} []
[2024-09-12T08:40:49.286745+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T08:40:49.368655+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test","serverVersion":"8.0.3","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test","serverVersion":"8.0.3","charset":"utf8"}} []
[2024-09-12T08:40:49.378035+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'week5api_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'week5api_test' at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)"} []
[2024-09-12T10:19:22.383368+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:19:22.383660+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:19:22.391727+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
[2024-09-12T10:22:37.605247+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:22:37.605588+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:22:37.612174+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
[2024-09-12T10:26:02.829375+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:26:02.829661+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:26:02.831845+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test_test","serverVersion":"8.0.3","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test_test","serverVersion":"8.0.3","charset":"utf8"}} []
[2024-09-12T10:26:02.832920+00:00] doctrine.DEBUG: Executing statement: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3 FROM category t0 WHERE t0.name = ? LIMIT 1 (parameters: array{"1":1}, types: array{"1":2}) {"sql":"SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3 FROM category t0 WHERE t0.name = ? LIMIT 1","params":{"1":1},"types":{"1":2}} []
[2024-09-12T10:26:02.841947+00:00] doctrine.DEBUG: Beginning transaction [] []
[2024-09-12T10:26:02.844092+00:00] doctrine.DEBUG: Executing statement: INSERT INTO product (name, price, quantity, description, category_id) VALUES (?, ?, ?, ?, ?) (parameters: array{"1":"test product2","2":20.9,"3":20,"4":"test product2","5":null}, types: array{"1":2,"2":2,"3":1,"4":2,"5":1}) {"sql":"INSERT INTO product (name, price, quantity, description, category_id) VALUES (?, ?, ?, ?, ?)","params":{"1":"test product2","2":20.9,"3":20,"4":"test product2","5":null},"types":{"1":2,"2":2,"3":1,"4":2,"5":1}} []
[2024-09-12T10:26:02.853311+00:00] doctrine.DEBUG: Rolling back transaction [] []
[2024-09-12T10:26:02.856345+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null" at ExceptionConverter.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 1048): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:115)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1048): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []
[2024-09-12T10:26:51.555190+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:26:51.555386+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:26:51.561049+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
[2024-09-12T10:40:24.077834+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:40:24.078013+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:40:24.089098+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
[2024-09-12T10:41:07.276831+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:41:07.277025+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:41:07.278385+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test_test","serverVersion":"8.0.3","charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"week5api_test_test","serverVersion":"8.0.3","charset":"utf8"}} []
[2024-09-12T10:41:07.279449+00:00] doctrine.DEBUG: Executing statement: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3 FROM category t0 WHERE t0.name = ? LIMIT 1 (parameters: array{"1":1}, types: array{"1":2}) {"sql":"SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3 FROM category t0 WHERE t0.name = ? LIMIT 1","params":{"1":1},"types":{"1":2}} []
[2024-09-12T10:41:07.287499+00:00] doctrine.DEBUG: Beginning transaction [] []
[2024-09-12T10:41:07.289967+00:00] doctrine.DEBUG: Executing statement: INSERT INTO product (name, price, quantity, description, category_id) VALUES (?, ?, ?, ?, ?) (parameters: array{"1":"test product2","2":20.9,"3":20,"4":"test product2","5":null}, types: array{"1":2,"2":2,"3":1,"4":2,"5":1}) {"sql":"INSERT INTO product (name, price, quantity, description, category_id) VALUES (?, ?, ?, ?, ?)","params":{"1":"test product2","2":20.9,"3":20,"4":"test product2","5":null},"types":{"1":2,"2":2,"3":1,"4":2,"5":1}} []
[2024-09-12T10:41:07.297590+00:00] doctrine.DEBUG: Rolling back transaction [] []
[2024-09-12T10:41:07.300146+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null" at ExceptionConverter.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 1048): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:115)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1048): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []
[2024-09-12T10:41:29.459533+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:41:29.459752+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:41:29.465959+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
[2024-09-12T10:56:39.038083+00:00] request.INFO: Matched route "api_productscreate_product". {"route":"api_productscreate_product","route_parameters":{"_route":"api_productscreate_product","_controller":"App\\Controller\\ProductController::createProduct"},"request_uri":"http://localhost/api/products/","method":"POST"} []
[2024-09-12T10:56:39.038275+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-09-12T10:56:39.048687+00:00] request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Undefined array key "Category"" at ProductController.php line 63 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Undefined array key \"Category\" at /Users/severin.kolakov/Desktop/cloning/Internship-RG/AssignmentsW5L1/src/Controller/ProductController.php:63)"} []
